include ../../../defs.mak

PLUGIN_NAME = classic_stick2btn
SOURCES = classic_stick2btn.c
LDLIBS += -lm
INST_DIR = $(CWIID_PLUGINS_DIR)

include $(COMMON)/include/plugin.mak

distclean: clean
	rm Makefile

.PHONY: distclean
